import Drink from "../drinks/models/Drink";

const drinks: Drink[] = [
    { id: 1, name: "Mojito", ingredients: ["Rum branco", "Açúcar", "Limão", "Hortelã", "Água com gás"], instructions: "Macere as folhas de hortelã com o açúcar e o suco de limão. Adicione rum e complete com água com gás. Mexa bem e decore com um ramo de hortelã." },
    { id: 2, name: "Margarita", ingredients: ["Tequila", "Triple sec", "Suco de limão", "Sal"], instructions: "Misture tequila, triple sec e suco de limão com gelo. Coe em um copo com borda de sal." },
    { id: 3, name: "Old Fashioned", ingredients: ["Bourbon", "Açúcar", "Angostura bitters", "Casca de laranja"], instructions: "Macere o açúcar com bitters e um pouco de água. Adicione o bourbon e gelo. Mexa e decore com a casca de laranja." },
    { id: 4, name: "Piña Colada", ingredients: ["Rum branco", "Creme de coco", "Suco de abacaxi", "Gelo"], instructions: "Bata todos os ingredientes com gelo no liquidificador até ficar homogêneo. Sirva em um copo gelado e decore com uma fatia de abacaxi." },
    { id: 5, name: "Martini", ingredients: ["Gin", "Vermute seco", "Azeitona ou twist de limão"], instructions: "Mexa o gin e o vermute com gelo. Coe em um copo gelado e decore com a azeitona ou o twist de limão." },
    { id: 6, name: "Caipirinha", ingredients: ["Cachaça", "Limão", "Açúcar", "Gelo"], instructions: "Macere o limão com açúcar. Adicione gelo e cachaça. Mexa bem." },
    { id: 7, name: "Negroni", ingredients: ["Gin", "Campari", "Vermute doce"], instructions: "Misture todos os ingredientes com gelo. Coe em um copo com gelo e decore com casca de laranja." },
    { id: 8, name: "Whiskey Sour", ingredients: ["Whiskey", "Suco de limão", "Açúcar", "Clara de ovo (opcional)"], instructions: "Bata todos os ingredientes com gelo. Coe e sirva. Decore com uma cereja." },
    { id: 9, name: "Batida de Coco", ingredients: ["Leite condensado", "Leite de coco", "Cachaça", "Gelo"], instructions: "Bata todos os ingredientes no liquidificador até ficar cremoso. Sirva gelado." },
    { id: 10, name: "Gin Tônica", ingredients: ["Gin", "Água tônica", "Limão"], instructions: "Despeje o gin sobre gelo. Adicione água tônica e mexa levemente. Decore com uma fatia de limão." },
    { id: 11, name: "Bloody Mary", ingredients: ["Vodka", "Suco de tomate", "Suco de limão", "Molho inglês", "Tabasco", "Sal de aipo", "Pimenta"], instructions: "Misture todos os ingredientes e sirva com gelo. Decore com um talo de aipo." },
    { id: 12, name: "Tequila Sunrise", ingredients: ["Tequila", "Suco de laranja", "Grenadine"], instructions: "Despeje tequila e suco de laranja sobre gelo. Adicione grenadine lentamente para criar o efeito de nascer do sol." },
    { id: 13, name: "Sex on the Beach", ingredients: ["Vodka", "Licor de pêssego", "Suco de laranja", "Suco de cranberry"], instructions: "Misture todos os ingredientes com gelo e sirva em um copo alto." },
    { id: 14, name: "Aperol Spritz", ingredients: ["Aperol", "Prosecco", "Água com gás"], instructions: "Misture Aperol e Prosecco sobre gelo. Adicione água com gás e mexa levemente. Decore com uma fatia de laranja." },
    { id: 15, name: "Batida de Morango", ingredients: ["Leite condensado", "Morango", "Vodka", "Gelo"], instructions: "Bata todos os ingredientes no liquidificador até ficar cremoso. Sirva gelado." },
    { id: 16, name: "Cuba Libre", ingredients: ["Rum", "Coca-Cola", "Limão"], instructions: "Misture o rum e a Coca-Cola sobre gelo. Esprema uma fatia de limão e mexa levemente." },
    { id: 17, name: "Manhattan", ingredients: ["Whiskey", "Vermute doce", "Angostura bitters"], instructions: "Misture todos os ingredientes com gelo. Coe em um copo gelado e decore com uma cereja." },
    { id: 18, name: "Irish Coffee", ingredients: ["Whiskey irlandês", "Café quente", "Açúcar", "Creme de leite"], instructions: "Misture o whiskey, o café e o açúcar. Adicione o creme levemente batido por cima." },
    { id: 19, name: "Batida de Abacaxi", ingredients: ["Abacaxi", "Leite condensado", "Vodka", "Gelo"], instructions: "Bata todos os ingredientes no liquidificador e sirva gelado." },
    { id: 20, name: "Caipiroska", ingredients: ["Vodka", "Limão", "Açúcar", "Gelo"], instructions: "Macere o limão com o açúcar. Adicione gelo e vodka. Mexa bem." },
    { id: 21, name: "Mint Julep", ingredients: ["Bourbon", "Hortelã", "Açúcar", "Água"], instructions: "Macere hortelã com açúcar e água. Adicione o bourbon e gelo. Mexa e decore com hortelã." },
    { id: 22, name: "Clericot", ingredients: ["Vinho branco", "Frutas picadas", "Licor", "Água com gás"], instructions: "Misture o vinho, as frutas e o licor. Complete com água com gás e sirva gelado." },
    { id: 23, name: "Mimosa", ingredients: ["Champanhe", "Suco de laranja"], instructions: "Misture o champanhe e o suco de laranja em partes iguais. Sirva gelado." },
    { id: 24, name: "Gin Fizz", ingredients: ["Gin", "Suco de limão", "Açúcar", "Água com gás"], instructions: "Bata o gin, o suco e o açúcar com gelo. Coe e complete com água com gás." },
    { id: 25, name: "Bellini", ingredients: ["Prosecco", "Purê de pêssego"], instructions: "Misture o prosecco com o purê de pêssego e sirva em uma taça." },
    { id: 26, name: "Espresso Martini", ingredients: ["Vodka", "Licor de café", "Café espresso"], instructions: "Bata todos os ingredientes com gelo e coe em uma taça." },
    { id: 27, name: "Blue Lagoon", ingredients: ["Vodka", "Blue curaçao", "Suco de limão"], instructions: "Misture os ingredientes com gelo e sirva em um copo alto." },
    { id: 28, name: "Batida de Maracujá", ingredients: ["Maracujá", "Leite condensado", "Cachaça", "Gelo"], instructions: "Bata todos os ingredientes no liquidificador até ficar cremoso." },
    { id: 29, name: "Kir Royal", ingredients: ["Champanhe", "Licor de cassis"], instructions: "Despeje o licor em uma taça e complete com champanhe." },
    { id: 30, name: "Tom Collins", ingredients: ["Gin", "Suco de limão", "Açúcar", "Água com gás"], instructions: "Misture gin, suco de limão e açúcar. Complete com água com gás." },
    { id: 31, name: "Long Island Iced Tea", ingredients: ["Vodka", "Tequila", "Rum", "Gin", "Triple sec", "Suco de limão", "Coca-Cola"], instructions: "Misture todos os ingredientes com gelo e adicione Coca-Cola." },
    { id: 32, name: "Pisco Sour", ingredients: ["Pisco", "Suco de limão", "Açúcar", "Clara de ovo"], instructions: "Bata todos os ingredientes com gelo e coe em um copo." },
    { id: 33, name: "Batida de Amendoim", ingredients: ["Amendoim", "Leite condensado", "Vodka", "Gelo"], instructions: "Bata todos os ingredientes no liquidificador." },
    { id: 34, name: "Sangria", ingredients: ["Vinho tinto", "Frutas", "Açúcar", "Água com gás"], instructions: "Misture todos os ingredientes e deixe na geladeira antes de servir." },
    { id: 35, name: "Caipiríssima", ingredients: ["Rum", "Limão", "Açúcar", "Gelo"], instructions: "Macere o limão com açúcar, adicione rum e gelo. Mexa bem." },
    { id: 36, name: "Dry Martini", ingredients: ["Gin", "Vermute seco"], instructions: "Misture o gin e o vermute com gelo e coe." },
    { id: 37, name: "Frozen Margarita", ingredients: ["Tequila", "Suco de limão", "Triple sec", "Gelo"], instructions: "Bata todos os ingredientes no liquidificador." },
    { id: 38, name: "French 75", ingredients: ["Gin", "Champanhe", "Suco de limão", "Açúcar"], instructions: "Misture gin, suco e açúcar. Complete com champanhe." },
    { id: 39, name: "Batida de Banana", ingredients: ["Banana", "Leite condensado", "Cachaça", "Gelo"], instructions: "Bata todos os ingredientes no liquidificador." },
    { id: 40, name: "Brandy Alexander", ingredients: ["Brandy", "Licor de cacau", "Creme de leite"], instructions: "Bata todos os ingredientes com gelo e coe." },
    { id: 41, name: "Rabo de Galo", ingredients: ["Cachaça", "Vermute"], instructions: "Misture os ingredientes com gelo e sirva." },
    { id: 42, name: "Batida de Manga", ingredients: ["Manga", "Leite condensado", "Vodka", "Gelo"], instructions: "Bata todos os ingredientes no liquidificador." },
    { id: 43, name: "Moscow Mule", ingredients: ["Vodka", "Suco de limão", "Ginger beer"], instructions: "Misture os ingredientes com gelo e decore com uma fatia de limão." },
    { id: 44, name: "Americano", ingredients: ["Campari", "Vermute doce", "Água com gás"], instructions: "Misture os ingredientes com gelo e complete com água com gás." },
    { id: 45, name: "Grasshopper", ingredients: ["Licor de menta", "Licor de cacau", "Creme de leite"], instructions: "Bata os ingredientes com gelo e coe." },
    { id: 46, name: "Batida de Morango com Leite", ingredients: ["Morango", "Leite condensado", "Leite", "Gelo"], instructions: "Bata tudo no liquidificador até ficar homogêneo." },
    { id: 47, name: "Caipilé", ingredients: ["Cachaça", "Limão", "Açúcar", "Picolé"], instructions: "Macere o limão com açúcar, adicione a cachaça e um picolé no copo." },
    { id: 48, name: "Batida de Uva", ingredients: ["Suco de uva", "Leite condensado", "Cachaça", "Gelo"], instructions: "Bata todos os ingredientes no liquidificador." },
    { id: 49, name: "Kir", ingredients: ["Vinho branco", "Licor de cassis"], instructions: "Misture o licor com o vinho branco e sirva." },
    { id: 50, name: "Clover Club", ingredients: ["Gin", "Suco de limão", "Xarope de framboesa", "Clara de ovo"], instructions: "Bata todos os ingredientes com gelo e coe em uma taça." }
  ];
  
export default drinks